---
title: "Calculate Fantasy Points"
output: html_document
---
```{r}
library(doParallel)
```

```{r setup, include=FALSE}
weekly_sums_df <- read.csv("../data/filled_summary_statistics.csv")
```

```{r}
names(weekly_sums_df)
```


#In Fantasy Football, each player earns points based on their performance. 
#Here we are picking some arbitrary numbers for how many fantasy points 1 of each metric is worth and then taking the dotproduct of the point values and the sum of the metrics.
```{r}
points <- data.frame(Assist=.25,PuntsBlocked=0,FGsBlocked=0, XPsBlocked=0,Fumble=0,
                     FumLost=-2,FrcFum=1,FumRec=2,FumTd=6,FumTdLen=0,Int=2,IntTd=6,
                     FGAtt=0,FGMade=3,FGMiss=-1,XPAtt=0,XPMade=1,KickRet=0,KickRetTD=6,
                     KickRetYd=.02,LenKickRetTD=0,PassYd=.05,PassTD=6,IntThrown=-3,
                     PassAtt=0,PassComp=.2,PassIncomp=-.1,PickSix=-6,PickSixLen=0,
                     Sacked=-1,SackedYds=0,PassDef=1,Penalty=-.25,PenaltyYds=-.01,
                     PntReturns=0,PntRetYd=.02,PuntReturnedTD=6,LenPuntReturnTD=0,
                     Punt=0, PuntYd=.01,PuntIn20=.1,TB=0,QBHit=.1,RecYd=.1,Rec=1,
                     Target=0,RecTD=6,RushYd=.1,RushTD=6,RushAtt=.1,Sack=1,SafetyForc=2,
                     Tackle=.5,TFL=.5)

write.csv(points, "../data/points.csv")
```

```{r}
notNan <- function(val){
  if (is.na(val)){
    return(0)
  }
  else{
    return(val)
  }
}
```

```{r}
weekly_sums_df$FPoints <-0
```

# ```{r}
# weekly_sums_df[1,"FPoints"] = weekly_sums_df[1,"FPoints"]+weekly_sums_df[1,"RushYd"]*points[1,"RushYd"]
# weekly_sums_df[1,"FPoints"] = weekly_sums_df[1,"FPoints"] + notNan(weekly_sums_df[1,"Sack"]) * points[1,"Sack"]
# ```


```{r}
registerDoParallel(cores=4)
future::plan("multisession")
for (i in 1:nrow(weekly_sums_df)){
  if (i%%100 == 0){print(i/nrow(weekly_sums_df))}
  for (name in c(names(points))){
    weekly_sums_df[i,"FPoints"] = weekly_sums_df[i,"FPoints"]+notNan(weekly_sums_df[i,name])*points[1,name]
  }
}
```

#Writes out the data with calculated Fantasy Points to a new csv
```{r}
write.csv(weekly_sums_df, "../data/weekly_fantasy_points.csv")
```